!Wing Commander MUSH/!wcnh_web-master/config/routes.rb
WcnhWeb::Application.routes.draw do
  devise_for :users

  root :to => "pages#homepage"
  
  get "pages" => "pages#index"
  get "recent_changes" => "pages#index"
  get "search" => "pages#index"
    
  get "pages/:name" => "pages#show", :as => "page"
  post "pages" => "admin/pages#create", :as => "pages"
  put "pages/:id" => "admin/pages#save", :as => "pages_save"
  
  namespace "admin" do
    get "pages" => "pages#index", :as => "pages"
    get "pages/:id/edit" => "pages#edit", :as => "pages_edit"
    get "pages/new" => "pages#new", :as => "pages_new"
    get "pages/:id/delete" => "pages#delete", :as => "pages_delete"
  end

  get "wanted" => "pages#wanted"
  get "rp" => "pages#rp"
  get "headlines" => "feeds#headlines"
  get "gmemits" => "feeds#gmemits"
  get "show_rss/:id" => "feeds#show"
  get "announcements" => "feeds#announcements"
  get "contracts" => "feeds#contracts"
  

  match "/intro" => redirect("/pages/introduction")
  match "/faq" => redirect("/pages/faq")
  match "/play" => redirect("/pages/begin-playing")
  match "/systems" => redirect("/pages/inhabited-systems")
  match "/systems/cabrea" => redirect("/pages/cabrea-system")
  match "/systems/midgard" => redirect("/pages/midgard-system")
  match "/systems/pembroke" => redirect("/pages/pembroke-system")
  match "/systems/vespus" => redirect("/pages/vespus-system")
  match "/races/human" => redirect("/pages/humans")
  match "/races/kilrathi" => redirect("/pages/kilrathi")
  match "/orgs/esc" => redirect("/pages/enigma-sector-consortium")
  match "/orgs/esc/vsi" => redirect("/pages/von-sprechen-industries")
  match "/orgs/esc/gc" => redirect("/pages/guinterin-combine/")
  match "/orgs/esc/tr" => redirect("/pages/taffin-reclamation")
  match "/orgs/kc" => redirect("/pages/kilrathi-commonwealth")
  match "/origins" => redirect("/pages/origins")
  match "/recent" => redirect("/pages/recent-history")
  match "/arcs" => redirect("/pages/running-arcs")

end

!Wing Commander MUSH/!wcnh_web-master/app/views/shared/_events.html.haml
%h2 Events
- @events.each do |event|
  .listing.first
    .wrap.when
      %span.month= event.date.strftime("%b")
      %span.date= event.date.day
    .wrap.details
      .title
        %h3= event.title
      .excerpt
        %p= event.info  

!Wing Commander MUSH/!wcnh_web-master/app/views/shared/_headlines.html.haml
%h2 Headline News (<a href="/headlines.rss">RSS Feed</a>)
- @headlines.each do |story|
  .listing.first
    .title
      %h3= story.title
    .excerpt
      %p= "#{story.created_at.to_datetime.to_ictime.strftime('%B %e, %Y')}<br><br>#{story.body.gsub("\n","<br>")}".html_safe

!Wing Commander MUSH/!wcnh_web-master/app/views/shared/_nav.html.haml
#nav.column.grid_6
  .row
    .column.grid_2
      %h2 The Game
      %ul
        %li
          %a{:href => '/pages/introduction/'} Introduction
        %li
          %a{:href => '/pages/guide/'} 
            %strong &raquo; Newbie Guide &laquo;
        %li
          %a{:href => '/pages/faq/'} Frequent Questions
        %li
          %a{:href => '/rp/'} RP Opportunities
    .column.grid_2
      %h2 The Setting
      %ul
        %li
          %a{:href => '/pages/inhabited-systems/'} Inhabited Systems
        %li
          %a{:href => '/pages/humans/'} Races
        %li
          %a{:href => '/pages/enigma-sector-consortium/'} Organizations
        %li
          %a{:href => '/wanted/'} Wanted List
        %li
          %a{:href => '/recent_changes'} Recent Entries
    .column.grid_2
      %h2 The Story
      %ul
        %li
          %a{:href => '/pages/origins/'} Origins
        %li
          %a{:href => '/pages/recent-history/'} Recent History
        %li
          %a{:href => '/pages/running-arcs/'} Running Arcs
        %li
          %a{:href => '/pages/logs/'} Featured Logs

!Wing Commander MUSH/!wcnh_web-master/app/views/shared/_page_list.html.haml
%tr
  %td= link_to page.title, "pages/#{page.urls.first}"
  %td= page.editor.nil? ? "" : page.editor.name
  %td= page.updated_at.strftime("%d %b %Y %H:%M %Z")
  -if page.versions.count > 1
    -change = page.text.length - page.versions[page.versions.count - 2].text.length
    -if change > 0
      %td= "#{change} additions"
    -else
      %td= "#{change.abs} deletions"
  -else
    %td= "New Page"

!Wing Commander MUSH/!wcnh_web-master/app/views/shared/_utility.html.haml
=form_tag '/search', method: :get do
  =text_field_tag(:term)
  =submit_tag('Search')
-if user_signed_in?
  Signed in as #{current_user.name} -
  =link_to("Logout", destroy_user_session_path, :method => 'delete') 
  | 
  =link_to("My Pages", admin_pages_path)
-else
  =link_to("Login", new_user_session_path)