!Wing Commander MUSH/!wcnh_web-master/config/routes.rb
WcnhWeb::Application.routes.draw do
  devise_for :users

  root :to => "pages#homepage"
  
  get "pages" => "pages#index"
  get "recent_changes" => "pages#index"
  get "search" => "pages#index"
    
  get "pages/:name" => "pages#show", :as => "page"
  post "pages" => "admin/pages#create", :as => "pages"
  put "pages/:id" => "admin/pages#save", :as => "pages_save"
  
  namespace "admin" do
    get "pages" => "pages#index", :as => "pages"
    get "pages/:id/edit" => "pages#edit", :as => "pages_edit"
    get "pages/new" => "pages#new", :as => "pages_new"
    get "pages/:id/delete" => "pages#delete", :as => "pages_delete"
  end

  get "wanted" => "pages#wanted"
  get "rp" => "pages#rp"
  get "headlines" => "feeds#headlines"
  get "gmemits" => "feeds#gmemits"
  get "show_rss/:id" => "feeds#show"
  get "announcements" => "feeds#announcements"
  get "contracts" => "feeds#contracts"
  

  match "/intro" => redirect("/pages/introduction")
  match "/faq" => redirect("/pages/faq")
  match "/play" => redirect("/pages/begin-playing")
  match "/systems" => redirect("/pages/inhabited-systems")
  match "/systems/cabrea" => redirect("/pages/cabrea-system")
  match "/systems/midgard" => redirect("/pages/midgard-system")
  match "/systems/pembroke" => redirect("/pages/pembroke-system")
  match "/systems/vespus" => redirect("/pages/vespus-system")
  match "/races/human" => redirect("/pages/humans")
  match "/races/kilrathi" => redirect("/pages/kilrathi")
  match "/orgs/esc" => redirect("/pages/enigma-sector-consortium")
  match "/orgs/esc/vsi" => redirect("/pages/von-sprechen-industries")
  match "/orgs/esc/gc" => redirect("/pages/guinterin-combine/")
  match "/orgs/esc/tr" => redirect("/pages/taffin-reclamation")
  match "/orgs/kc" => redirect("/pages/kilrathi-commonwealth")
  match "/origins" => redirect("/pages/origins")
  match "/recent" => redirect("/pages/recent-history")
  match "/arcs" => redirect("/pages/running-arcs")

end

!Wing Commander MUSH/!wcnh_web-master/app/views/admin/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2 #{pluralize(@page.errors.count, "error")} prohibited this page from being saved:
      %ul
      - @page.errors.full_messages.each do |msg|
        %li=msg
  %table
    %tr
      %td
        Page title:
      %td=f.text_field :title
    %tr
      %td
        Page body:
        %br
        %small=link_to "(Markdown quick reference)", "http://www.darkcoding.net/software/markdown-quick-reference/", :target => "blank"
      %td=f.text_area :text, :size => "80x20"
    %tr
      %td Page URLs:
      %td=@page.urls
    %tr
      %td Page sidebars:
      %td=@page.sidebars
    %tr
      %td
      %td
        =f.submit

!Wing Commander MUSH/!wcnh_web-master/app/views/admin/pages/edit.html.haml
-title_and_h1 "Editing #{@page.title}"
= render 'form'

!Wing Commander MUSH/!wcnh_web-master/app/views/admin/pages/index.html.haml
-title_and_h1 "Edit Pages"

.column.grid_12.body
  %table
    %tr
      %th Title
      %th Primary URL
      %th Sidebar(s)
      %th Revision
      %th Last Updated
      %th Links
    -@pages.each do |page|
      %tr
        %td= page.title
        %td= page.urls[0]
        %td= page.sidebars
        %td= page.version
        %td= page.updated_at
        %td
          =link_to "Edit", admin_pages_edit_path(page)
          =link_to "Delete", admin_pages_delete_path(page), :confirm => "Are you sure? This REALLY can't be undone."

  %p=link_to content_tag(:span, "Create new page"), admin_pages_new_path, :class => "bigbutton"

!Wing Commander MUSH/!wcnh_web-master/app/views/admin/pages/new.html.haml
-title_and_h1 "Create New Page"
= render 'form'