!Wing Commander MUSH/!wcnh_web-master/config/routes.rb
WcnhWeb::Application.routes.draw do
  devise_for :users

  root :to => "pages#homepage"
  
  get "pages" => "pages#index"
  get "recent_changes" => "pages#index"
  get "search" => "pages#index"
    
  get "pages/:name" => "pages#show", :as => "page"
  post "pages" => "admin/pages#create", :as => "pages"
  put "pages/:id" => "admin/pages#save", :as => "pages_save"
  
  namespace "admin" do
    get "pages" => "pages#index", :as => "pages"
    get "pages/:id/edit" => "pages#edit", :as => "pages_edit"
    get "pages/new" => "pages#new", :as => "pages_new"
    get "pages/:id/delete" => "pages#delete", :as => "pages_delete"
  end

  get "wanted" => "pages#wanted"
  get "rp" => "pages#rp"
  get "headlines" => "feeds#headlines"
  get "gmemits" => "feeds#gmemits"
  get "show_rss/:id" => "feeds#show"
  get "announcements" => "feeds#announcements"
  get "contracts" => "feeds#contracts"
  

  match "/intro" => redirect("/pages/introduction")
  match "/faq" => redirect("/pages/faq")
  match "/play" => redirect("/pages/begin-playing")
  match "/systems" => redirect("/pages/inhabited-systems")
  match "/systems/cabrea" => redirect("/pages/cabrea-system")
  match "/systems/midgard" => redirect("/pages/midgard-system")
  match "/systems/pembroke" => redirect("/pages/pembroke-system")
  match "/systems/vespus" => redirect("/pages/vespus-system")
  match "/races/human" => redirect("/pages/humans")
  match "/races/kilrathi" => redirect("/pages/kilrathi")
  match "/orgs/esc" => redirect("/pages/enigma-sector-consortium")
  match "/orgs/esc/vsi" => redirect("/pages/von-sprechen-industries")
  match "/orgs/esc/gc" => redirect("/pages/guinterin-combine/")
  match "/orgs/esc/tr" => redirect("/pages/taffin-reclamation")
  match "/orgs/kc" => redirect("/pages/kilrathi-commonwealth")
  match "/origins" => redirect("/pages/origins")
  match "/recent" => redirect("/pages/recent-history")
  match "/arcs" => redirect("/pages/running-arcs")

end

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/homepage.html.haml
-title "Homepage"
#home.column.grid_12
  .row
    .lead.column.grid_12
      %p Let your imagination run wild in our interactive storytelling universe.

  .row
    .sublead.column.grid_12
      %p
        Wing Commander: New Horizon MUSH is a text-based storytelling/roleplaying community, <br />
        set in the Wing Commander video game universe. It's 100% free to play and easy to get started!<br />
        Check the <a href="/pages/introduction/">Introduction</a> for more information, read our other pages, and <a href="/pages/begin-playing/">begin playing!</a>

  .row
    .events.column.grid_6
      =render :partial => "shared/events"
    .reports.column.grid_6
      =render :partial => "shared/headlines"

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/index.html.haml
-title_and_h1 @title

.column.grid_12.body
  %table
    %tr
      %th Title
      %th Author
      %th Last Update
      %th Changes
    =render partial: "shared/page_list", collection: @pages, as: :page

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/missingpage.html.haml
=content_for :page_title, "404 - Page Not Found"
.error
  %p Sorry! That page doesn't exist.

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/rp.haml
-title_and_h1 "Roleplaying Opportunities"

.column.grid_9.body
  -if !@rpitems then
    %p
      Roleplaying Opportunities are the New Horizon version of Craigslist.  Maybe you're looking for a character concept to jump start your imagination.
      Or maybe you're just looking for an ongoing plot to join.  Whatever the case, the Roleplaying Opportunities list is a collection point for any and 
      all ideas related to roleplaying.  The items listed here are linked to the in-game '+rp' system, which allows players to post their ideas while 
      they're online.  Posts are categorized as follows:
    %p
      -@rpcats.each do |i|
        %strong= link_to(i.name, rp_path(:category => i.name))
        =" - #{i.desc}"
        %br
    -else
      %h3= "#{@cat.first.name} - #{@cat.first.desc}"
      %br
      -@rpitems.each do |i|
        %h4=i.title
        %p
          %strong Posted:
          = i.created_at.strftime("%A, %B %e %Y")
          %br
          %strong Details:
          =i.info

.column.sidebar
  .item
    %h3 Categories
    -@rpcats.each do |i|
      =link_to(i.name, rp_path(:category => i.name)) + " (#{i.items.count} posts)"
      %br

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/show.html.haml
-title_and_h1 @page.title

-if @sidebars.length > 0
  .column.grid_9.body=@page.to_html.html_safe
-else
  .column.grid_12.body=@page.to_html.html_safe

-if @sidebars.length
  .column.sidebar
    -@sidebars.each do |sidebar|
      .item
        %h3=sidebar.title
        .text=sidebar.to_html.html_safe

-if user_signed_in? && can_edit(@page)
  =link_to "Edit Page", admin_pages_edit_path(@page)

!Wing Commander MUSH/!wcnh_web-master/app/views/pages/wanted.haml
-title_and_h1 "Wanted List"

.column.grid_12
  .body
    - @wanted.each do |i|
      %h4= "Wanted Entry #{i._id}"
      %p
        %strong Name: 
        = "#{i.name}"
        %br
        %strong Bounty: 
        = "#{number_with_delimiter(i.amount, :delimiter => ",")}"
        %br
        %strong Contact:
        = "#{i.contact}"
        %br
        %strong Details: 
        = "#{i.info}"